name: Deploy Images to GHCR

on:
  push:
    branches:
      - master 
jobs:
      push_to_registry:
        name: lms app - payment image push to repo
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@master

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ${{ secrets.ACR_ENDPOINT }}
              username: ${{ secrets.ACR_USERNAME }}
              password: ${{ secrets.ACR_PASSWORD }}
              
          - name: 'Build and push Docker Image'
            uses: docker/login-action@v4
            run: |
              context: payment/
              push: true
              tags: lmsapprepo.azurecr.io/lmsapprepo:v0.1.0
              docker build . --tag lmsapprepo.azurecr.io/lmsapprepo:v0.1.0
              docker push lmsapprepo.azurecr.io/lmsapprepo:v0.1.0